# Generated by Django 5.0 on 2024-03-18 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0006_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssa_app.staff'),
        ),
    ]
