# Generated by Django 5.0 on 2024-03-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0007_alter_subject_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='sub_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='short_name',
            new_name='sub_short_name',
        ),
    ]
