# Generated by Django 5.0 on 2024-03-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0008_rename_name_subject_sub_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_short_name',
            new_name='short_sub_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='staff',
            new_name='staff_id',
        ),
    ]
