# Generated by Django 5.0 on 2024-03-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0009_rename_course_subject_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='short_sub_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_name',
            new_name='short_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
