# Generated by Django 5.0 on 2024-03-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0010_rename_course_id_subject_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
