# Generated by Django 5.0 on 2024-03-20 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0011_alter_subject_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssa_app.staff')),
            ],
        ),
    ]
