# Generated by Django 5.0 on 2024-03-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0012_staff_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='short_notification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff_notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
