# Generated by Django 5.0 on 2024-03-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0016_staff_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_leave',
            name='date',
        ),
        migrations.AddField(
            model_name='staff_leave',
            name='s_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
