# Generated by Django 5.0 on 2024-03-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0018_staff_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_feedback',
            old_name='staff_id',
            new_name='staffid',
        ),
    ]
