# Generated by Django 5.0 on 2024-04-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0020_rename_staffid_staff_feedback_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_end',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_start',
            field=models.DateField(max_length=50),
        ),
    ]
