# Generated by Django 5.0 on 2024-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0021_alter_session_session_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_end',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_start',
            field=models.CharField(max_length=50),
        ),
    ]
