# Generated by Django 5.0 on 2024-04-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0023_forgot_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgot_password',
            name='forgot_password_token',
            field=models.CharField(max_length=100),
        ),
    ]
