# Generated by Django 3.2.25 on 2024-04-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0025_attendance_attendance_report_student_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance_date',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student_result',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student_result',
            name='subject_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendance_Report',
        ),
        migrations.DeleteModel(
            name='Student_Result',
        ),
    ]
