# Generated by Django 3.2.25 on 2024-04-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0027_attendance_attendance_report_student_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='attendance_date',
        ),
        migrations.RemoveField(
            model_name='attendance_report',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendance_Report',
        ),
    ]
