# Generated by Django 5.0 on 2024-04-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0029_auto_20240422_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_notification',
            name='short_notification',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
