# Generated by Django 4.1.13 on 2024-04-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssa_app', '0030_student_notification_short_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('firstSubject', models.CharField(max_length=200)),
                ('secondSubject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PopularCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images/PopularCoursesImages')),
                ('timing', models.FloatField()),
                ('price', models.IntegerField()),
                ('instructorName', models.CharField(max_length=100)),
                ('time', models.FloatField()),
                ('studentsNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/TeamImages')),
                ('timing', models.FloatField()),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images/TestimonialImages')),
                ('feedback', models.TextField()),
            ],
        ),
    ]
